 <?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Framework\View\Element\Template $block */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get(\Magento\Customer\Model\Session::class);
?>

<div id="employee-listing-wrapper"
     data-bind="scope: 'employeeListing'">

    <script>
        window.isCustomerLoggedIn =
            <?= $customerSession->isLoggedIn() ? 'true' : 'false' ?>;
    </script>

    <div data-bind="template: {
        name: 'Adobe_Employee/employee-listing'
    }"></div>

</div>

<script type="text/x-magento-init">
{
    "#employee-listing-wrapper": {
        "Magento_Ui/js/core/app": {
            "components": {
                "employeeListing": {
                    "component": "Adobe_Employee/js/employee-listing"
                }
            }
        }
    }
}
</script>